### ISSUE TITLE
Change the black top bar color

### ISSUE THREAD

**Issue by jonathanfontaine** [akshaaatt/Onboarding-Android#5]
Hi,

First I want to thank you for your great work, it saves us a lot of time 💪

I'm wondering if there is a way to customize the top bar color which is actually black :
![image](https://github.com/akshaaatt/Onboarding-Android/assets/10338401/8c82bb4d-e294-48b0-9408-b26739c56086)

**Comment by akshaaatt** [comment]
Hi @jonathanfontaine ! Thanks for the kind words :)
I have updated the example to show how to change the status bar color. Please follow that.

**Comment by jonathanfontaine** [comment]
@akshaaatt Thanks a lot, works like a charm!
